version: "3.7"
services:
  app:
    build:
      args:
        user: rjbgaspar
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-test
    container_name: laravel-test-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel_default
  db:
    image: mysql:8.0
    container_name: laravel-test-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel_default
  nginx:
    image: nginx:alpine
    container_name: laravel-test-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel_default
  keycloak:
      image: quay.io/keycloak/keycloak:19.0.1
      command: ["start-dev --import-realm"]
      volumes:
          - ./docker-compose/realm-config:/opt/keycloak/data/import
      environment:
          - KC_DB=dev-file
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
          - KC_FEATURES=scripts
          - KC_HTTP_PORT=9080
          - KC_HTTPS_PORT=9443
      ports:
          - 9080:9080
          - 9443:9443
      networks:
          - laravel_default
networks:
    laravel_default:
        driver: bridge
